param(
  [string]$RegistryPath = (Join-Path $PSScriptRoot '../registries/ai-team/registry.yaml'),
  [string]$OutputPath = (Join-Path $PSScriptRoot '../registries/ai-team/AI-TEAM-LIST.md')
)

$ErrorActionPreference = 'Stop'

function Convert-YamlScalar([string]$Value) {
  $value = $Value.Trim()
  if ($value.StartsWith('"') -and $value.EndsWith('"')) { return $value.Substring(1, $value.Length - 2) }
  return $value
}

function Convert-InlineList([string]$Value) {
  $value = $Value.Trim()
  if ($value -eq '[]') { return @() }
  if (-not ($value.StartsWith('[') -and $value.EndsWith(']'))) { throw "Expected inline YAML list: $value" }
  $inner = $value.Substring(1, $value.Length - 2)
  return @($inner -split '\s*,\s*' | ForEach-Object { Convert-YamlScalar $_ })
}

$records = [System.Collections.Generic.List[hashtable]]::new()
$current = $null
foreach ($line in Get-Content -LiteralPath $RegistryPath -Encoding UTF8) {
  if ($line -match '^  - ai_id:\s*(.+)$') {
    if ($null -ne $current) { $records.Add($current) }
    $current = @{}
    $current.ai_id = Convert-YamlScalar $Matches[1]
    continue
  }
  if ($null -ne $current -and $line -match '^    ([a-z_]+):\s*(.*)$') {
    $current[$Matches[1]] = Convert-YamlScalar $Matches[2]
  }
}
if ($null -ne $current) { $records.Add($current) }

$required = @(
  'ai_id','nickname','official_name','provider','role','mission','responsibilities','strengths','weaknesses','tools',
  'started_on','usage_status','plan_name','environment','connection_method','permission_level',
  'app_ids','collaborator_ai_ids','document_references','readme_ai_reference','owner_role',
  'updated_on','updated_by_role','last_reviewed_on'
)
$seen = @{}
foreach ($record in $records) {
  foreach ($field in $required) {
    if (-not $record.ContainsKey($field) -or [string]::IsNullOrWhiteSpace($record[$field])) { throw "Missing $field for $($record.ai_id)" }
  }
  if ($record.ai_id -notmatch '^AI-[0-9]{3}$') { throw "Invalid AI ID: $($record.ai_id)" }
  if ($seen.ContainsKey($record.ai_id)) { throw "Duplicate AI ID: $($record.ai_id)" }
  $seen[$record.ai_id] = $true
}

$allowedStatuses = @('active', 'suspended', 'retired')
$allowedPermissions = @('observe', 'draft', 'execute_limited', 'execute_approved')
foreach ($record in $records) {
  if ($record.usage_status -notin $allowedStatuses) { throw "Invalid usage_status for $($record.ai_id): $($record.usage_status)" }
  if ($record.permission_level -notin $allowedPermissions) { throw "Invalid permission_level for $($record.ai_id): $($record.permission_level)" }
  foreach ($dateField in @('started_on','updated_on','last_reviewed_on')) {
    if ($record[$dateField] -ne 'unknown' -and $record[$dateField] -notmatch '^[0-9]{4}-[0-9]{2}-[0-9]{2}$') { throw "Invalid $dateField for $($record.ai_id)" }
  }
  foreach ($appId in (Convert-InlineList $record.app_ids)) {
    if ($appId -notmatch '^APP-[0-9]{4}$') { throw "Invalid app ID for $($record.ai_id): $appId" }
  }
  foreach ($aiId in (Convert-InlineList $record.collaborator_ai_ids)) {
    if ($aiId -notmatch '^AI-[0-9]{3}$') { throw "Invalid collaborator AI ID for $($record.ai_id): $aiId" }
    if (-not $seen.ContainsKey($aiId)) { throw "Unknown collaborator AI ID for $($record.ai_id): $aiId" }
  }
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# AI Team List')
$lines.Add('')
$lines.Add('> Generated from `registry.yaml`. Do not edit this file directly.')
$lines.Add('')
$lines.Add('| AI ID | Nickname | Official name | Provider | Role | Status | App IDs | Updated on |')
$lines.Add('|---|---|---|---|---|---|---|---|')
foreach ($record in ($records | Sort-Object { $_.ai_id })) {
  if ($record.usage_status -notin $allowedStatuses) { throw "Invalid usage_status for $($record.ai_id): $($record.usage_status)" }
  $apps = (Convert-InlineList $record.app_ids) -join ', '
  $cells = @($record.ai_id, $record.nickname, $record.official_name, $record.provider, $record.role, $record.usage_status, $apps, $record.updated_on)
  $cells = $cells | ForEach-Object { ([string]$_).Replace('|', '\|').Replace("`r", ' ').Replace("`n", ' ') }
  $lines.Add('| ' + ($cells -join ' | ') + ' |')
}

[IO.File]::WriteAllLines([IO.Path]::GetFullPath($OutputPath), $lines, [Text.UTF8Encoding]::new($false))
Write-Output "Generated $OutputPath ($($records.Count) AI members)."
